### PR TITLE
Fix terraform message streaming

### LINKED ISSUE #555: Terraform apply does not stream output
### Expected behavior
`terraform` lifecycle step should stream output to browser while `apply` is in progress

### Actual behavior
After a couple minutes of work creating a cluster on AKS, it just shows `terraform apply`.
ship-terraform-apply

### Information

- Ship version: 
```
{
    "git": "cdb9646",
    "buildTime": "2018-09-12T15:15:41Z"
}
```
- Docker version: 18.06.1-ce
- Command line run:
`ship app --log-level=debug --runbook=release.yml`

### Steps to reproduce the behavior

1. Save `release.yaml`:
```
---¬
assets:¬
  v1:¬
    - azure_aks:¬
        tenant_id: '{{repl ConfigOption "azure_tenant_id" }}'¬
        subscription_id: '{{repl ConfigOption "azure_subscription_id" }}'¬
        service_principal_id: '{{repl ConfigOption "azure_service_principal_id" }}'¬
        service_principal_secret: '{{repl ConfigOption "azure_service_principal_secret" }}'¬
        resource_group_name: '{{repl ConfigOption "azure_resource_group_name" }}'¬
        location: '{{repl ConfigOption "azure_location" }}'¬
        cluster_name: "aksqa"¬
        kubernetes_version: "1.11.2"¬
        node_count: "1"¬
        node_type: "Standard_D1_v2"¬
¬
config:¬
  v1:¬
    - name: Azure¬
      title: Azure¬
      description: Azure configuration and credentials¬
      items:¬
      - name: azure_tenant_id¬
        title: Tenant ID¬
        type: text¬
      - name: azure_subscription_id¬
        title: Subscription ID¬
        type: text¬
      - name: azure_service_principal_id¬
        title: Service Principal ID¬
        type: text¬
      - name: azure_service_principal_secret¬
        title: Service Principal Secret¬
        type: password¬
      - name: azure_resource_group_name¬
        title: Resource Group¬
        type: text¬
      - name: azure_location¬
        title: Resource Group Location¬
        type: text¬
¬
lifecycle:¬
  v1:¬
    - config: {}¬
    - render: {}¬
    - terraform: {}¬
    - message:¬
        level: warn¬
        contents: Done
```
2. Run `ship app --runbook=release.yml` and fill in config with working Azure credentials.

### PR DESCRIPTION
**Pull request by Rob0h**
What I Did
------------
Fix #555 

How I Did it
------------
- Continuously listen for messages on `PushStreamStep`

How to verify it
------------
- Run `ship` with a `terraform` lifecycle step

Description for the Changelog
------------
Fix terraform message streaming

Picture of a Boat (not required but encouraged)
------------
⛵️

### CODE REVIEW

File: pkg/lifecycle/daemon/statusonly/daemon.go [hunk 1]
```diff
@@ -34,10 +34,7 @@ func (d *StatusReceiver) ClearProgress() {
 
 func (d *StatusReceiver) PushStreamStep(ctx context.Context, messages <-chan daemontypes.Message) {
 	debug := level.Debug(log.With(d.Logger, "method", "pushStreamStep"))
-	select {
-	case <-ctx.Done():
-		debug.Log("event", "ctx.Done", "err", ctx.Err())
-	case msg := <-messages:
+	for msg := range messages {
```
Comment (Rob0h) [inline pkg/lifecycle/daemon/statusonly/daemon.go]: not immediately obvious here but we only need to listen to messages on this channel until it's closed, which happens before the context is finished

Comment (dexhorthy) [reply pkg/lifecycle/daemon/statusonly/daemon.go]: I think we might lose some cancellation logic here?

Comment (Rob0h) [reply pkg/lifecycle/daemon/statusonly/daemon.go]: discussed irl - cancellation will be taken care of by executor
