### PR TITLE
Serialize metadata to state

### LINKED ISSUE #527: Ship init with replicated apps should store the app details in state.json
### Expected behavior
Customer ID, Installation ID, release version and content hash should all be stored in `.ship/state.json` as with non-replicated apps.

### Actual behavior
Only config items are stored in `.ship/state.json`.

### Information

- Ship version: master as of https://github.com/replicatedhq/ship/commit/ebb027556d4c3fbaa7e407491188e42f7a6938da
- Command line run: `ship init staging.replicated.app/some-cool-ci-tool?installation_id=<INSTALLATION_ID>&customer_id=<CUSTOMER_ID>`

### Steps to reproduce the behavior

1. Look at the expected [.ship/state.json](https://github.com/replicatedhq/ship/blob/ebb027556d4c3fbaa7e407491188e42f7a6938da/integration/init_app/github-template-func/expected/.ship/state.json) files in the init_app integration tests.

### PR DESCRIPTION
**Pull request by Rob0h**
What I Did
------------
- Write version, icon, name to state
- Fix #527 
- Supersedes #558, #559

How I Did it
------------
- Add `SerializeMetadata` to `Manager`

How to verify it
------------
- Test

Description for the Changelog
------------
Serialize metadata to state

Picture of a Boat (not required but encouraged)
------------
🛶

### CODE REVIEW

File: pkg/ship/ship.go [hunk 1]
```diff
@@ -152,6 +154,19 @@ func (s *Ship) Execute(ctx context.Context) error {
...
+	if stateFilePath != "" {
+		debug.Log("phase", "move", "state-file", stateFilePath)
+		stateFile, err := s.FS.ReadFile(stateFilePath)
+		if err != nil {
+			return errors.Wrap(err, "read state-file")
+		}
+		if err := s.FS.WriteFile(constants.StatePath, stateFile, 0644); err != nil {
+			return errors.Wrap(err, "write passed state file to constants.StatePath")
+		}
+	}
```
Comment (laverya) [inline pkg/ship/ship.go]: This is a much simpler solution than we had had before
I like it
